### ISSUE TITLE
ook.lite ?

### ISSUE THREAD

**Issue by repsorp** [VR-25/migrator#2]
hi,

Is it a typo and if not why ook.lite instead of facebook.lite ?

```
--help

USAGE EXAMPLES

Backup Facebook Lite and Instagram (apps and data)
migrator -b ook.lite,instagram
```

**Comment by VR-25** [comment]
`migrator -b [egrep regex pattern]`
_ook.lite_ matches _com.facebook.lite_, like in `echo com.facebook.lite | grep -E ook.lite`
